### ISSUE TITLE
link to 'csv_info_file' does not work

### ISSUE THREAD

**Issue by tianyu0523** [lasseufpa/ITU-Challenge-ML5G-PHY#2]
When I click the link to 'csv_info_file' does not work, it shows 'file not found'.

**Comment by AiltonOliveir** [comment]
Thanks for the warning. The link will be fix.
Until there you can found more informations about datasets in https://www.lasse.ufpa.br/raymobtime/
and all files of baseline dataset in https://nextcloud.lasseufpa.org/s/7FrX2883E4yorbB?path=%2FRaymobtime_s008

**Comment by tianyu0523** [comment]
Thanks for your reply. I also found that the email 'ai5gchallenge@listas.ufpa.br' does not exist.

**Comment by tianyu0523** [comment]
> Thanks for the warning. The link will be fix.
> Until there you can found more informations about datasets in https://www.lasse.ufpa.br/raymobtime/
> and all files of baseline dataset in https://nextcloud.lasseufpa.org/s/7FrX2883E4yorbB?path=%2FRaymobtime_s008

Thanks for your reply. I also found that the email 'ai5gchallenge@listas.ufpa.br' does not exist.
